In [1]:
import numpy as np

In [2]:
# Create 1D array of numers from 0 to 9
ls=[0,1,2,3,4,5,6,7,8,9]
arr=np.array(ls)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
# create 2D array of shape (3,3) with all elements 1.
A=np.ones((3,3), dtype=int)
A

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [32]:
# Generate an numpy array of 15 random integers between 10 and 50
B=np.array([11,12,13,14,15,25,26,27,28,29,30,41,42,43,44])
B

array([11, 12, 13, 14, 15, 25, 26, 27, 28, 29, 30, 41, 42, 43, 44])

In [12]:
# create an array of 5 evenly spaced number between 0 and 1(indusive)
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [14]:
#Create a 4*4 identity matrix using numpy.
A= np.zeros((4,4), dtype=int)
for i in range(4):
    A[i][i]=1
print(A)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [17]:
# create an array from the list [10,20,30,40] and changed the data type to float
lst=[10,20,30,40]
arr1=np.array(lst)
array=arr1.astype(float)
print(array)
print(arr1)

[10. 20. 30. 40.]
[10 20 30 40]


In [24]:
# create a 3*3 array with 10 values from 1 to 9, then extract the second column
arr2=np.arange(1,10).reshape(3,3)
col=arr2[:,1]
print(arr2)
print("second column:",col)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
second column: [2 5 8]


In [27]:
# Create 1D array with 10 elements and reshape it into a 2*5 matrix
arr4=np.array([1,2,3,4,5,6,7,8,9,10])
re_arr=arr4.reshape(2,5)
print(arr4)
print(re_arr)

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [29]:
# create two 2*2 matrices perform matrix multiplication
X=np.array([[1,2],[3,4]])
Y=np.array([[2,3],[1,4]])
mul=X*Y
print("Array 1:",X)
print("Array 2:",Y)
print("Multiplication:",mul)

Array 1: [[1 2]
 [3 4]]
Array 2: [[2 3]
 [1 4]]
Multiplication: [[ 2  6]
 [ 3 16]]


In [31]:
# given the array arr=np.array([5,12,7,18,3]),replace all values greater than 10 with 100.
arr5=np.array([5,12,7,18,3])
print("given array:",arr5)
arr5[arr5>10]=100
print(arr5)

given array: [ 5 12  7 18  3]
[  5 100   7 100   3]
